### PR TITLE
Merge pull request #1 from msargentTeachingMaterials/master

### PR DESCRIPTION
**Pull request by csulaka**
07102017

### CODE REVIEW

**Comment by csulaka** [comment]
pull for hw3

**Comment by msargentTeachingMaterials** [comment]
What are you trying to post? This isn't the place to submit homework.

**Comment by csulaka** [comment]
i was trying to pull your most update version to mine, seem like this is not a right way. Hope I didn't mass up yours. I will try to figure it out how to get the newest version of your work.

**Comment by msargentTeachingMaterials** [comment]
go to the directory where your cloned repo is, then git pull origin master

**Comment by mesargent** [comment]
You need to fork this repo into your own Github account, then push to that.

**Comment by msargentTeachingMaterials** [comment]
No student changes allowed.

**Pull request closed without merging**
